## create test entity
POST http://localhost:3000/test_entity
content-type: application/json

{
    "name": "Test"
}

###

## get test entities
GET http://localhost:3000/test_entity
content-type: application/json

###

GET http://localhost:3000/users
content-type: application/json

###


## view test entity
GET http://localhost:3000/test_entity/2
content-type: application/json

###

## update test entity
PUT http://localhost:3000/test_entity
content-type: application/json

{
    "id": 2,
    "name": "Test6"
}

###

## delete test entity
DELETE http://localhost:3000/test_entity/1
content-type: application/json

###