## create test entity
POST http://localhost:3000/test_entity
content-type: application/json

{
    "name": "Test"
}

###

## get test entities
GET http://localhost:3000/test_entity
content-type: application/json

###

GET https://www.google.com

### get complaints
GET http://192.168.43.44:5001/complaints/paginated
content-type: application/json

###

GET http://localhost:3000/users
content-type: application/json

###


## view test entity
GET http://localhost:3000/test_entity/2
content-type: application/json

###

## update test entity
PUT http://localhost:3000/test_entity
content-type: application/json

{
    "id": 2,
    "name": "Test6"
}

###

## delete test entity
DELETE http://localhost:3000/test_entity/1
content-type: application/json

### create test entity
POST https://api.stolets.dev/pos-messaging/v1/send-mail
content-type: application/json

{
    "receiver": "victordanny57@gmail.com",
    "msg":"Hello world."
}

### GET PROPERTIES
GET http://192.168.43.44:5001/entities/paginated

###