import 'dotenv/config';
export const CONSTANTS = {
  NODE_ENV: process.env.NODE_ENV!,
  LOCALSTACK_HOST: process.env.LOCALSTACK_HOST!,
  PASSWORD_RESET_TOKEN_EXPIRES_IN: 360,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
};
