export const DB_TYPES = {
  repositories: {
    Repository: 'Repository',
    UsersRepositoryImpl: 'UsersRepositoryImpl',
    OfferingRepositoryImpl: 'OfferingRepositoryImpl',
    ReactionRepositoryImpl: 'ReactionRepositoryImpl',
    ScheduleRepositoryImpl: 'ScheduleRepositoryImpl',
    UserOfferingRepositoryImpl: 'UserOfferingRepositoryImpl',
    UserTenancyAgreementRepositoryImpl: 'UserTenancyAgreementRepositoryImpl',
    TenancyAgreementRepositoryImpl: 'TenancyAgreementRepositoryImpl',
    PaymentRepositoryImpl: 'PaymentRepositoryImpl',
    PaymentMethodRepositoryImpl: 'PaymentMethodRepositoryImpl',
    PaymentCategoryRepositoryImpl: 'PaymentCategoryRepositoryImpl',
    ApplicationRepositoryImpl: 'ApplicationRepositoryImpl',
    ComplaintRepositoryImpl: 'ComplaintRepositoryImpl',
    BusinessRepositoryImpl: 'BusinessRepositoryImpl',
    UserBusinessRepositoryImpl: 'UserBusinessRepositoryImpl',
    MessageRepositoryImpl: 'MessageRepositoryImpl',
    RequestRepositoryImpl: 'RequestRepositoryImpl',
  },
};
